my_tupla=("Juna",4,56,1990)
my_list=list(my_tupla)
print(my_tupla[1])
print(my_list)
print(my_tupla)
#my_tupla2=tuple(my_list)
print("juan" in my_tupla)
print(my_tupla.count(56))
print(len(my_tupla))
name,day,age,year=my_tupla
print(name)
print(day)
print(age)
print(year)
